### ISSUE TITLE
no permission to create github pages

### ISSUE THREAD

**Issue by TAndras** [Teaching-projects/-SZE-MOSZE-2020-BDFANS#7]
A első feladat megoldásához nem tudok a doxygen által a gh-pages branchre generált html-ből github pagest csinálni, mert nincs jogosultságom a projekt beállításaihoz, és ezáltal a github pages beállításához sem.

**Comment by hegyhati** [comment]
kisse megkestetek vele, de beallitottam.

**Comment by vizvezetek** [comment]
@hegyhati Valami valszeg félre ment. 
https://teaching-projects.github.io/-SZE-MOSZE-2020-BDFANS

**Comment by hegyhati** [comment]
Ez tenyleg fura, hogy ket reponal is. no midnegy, most elmeletileg (megint) beallitottam. HA oke, lezarhatjatok.
